config/routes.rb
Bru::Application.routes.draw do
  resources :people
  resources :categories, :only => [:index, :show]
  resources :articles do
    resources :comments, :only => [:create, :update, :destroy]
    member do
      put :approve
      put :unapprove
    end
  end

  get 'signup' => 'people#new', :as => :signup
  get 'signin' => 'sessions#new', :as => :signin
  delete 'signout' => 'sessions#destroy', :as => :logout
  resource :session, :only => [:new, :create, :destroy]

  # root :to => "categories#index"
  match "/" => "categories#index", :as => :root
  # match '/activate/:activation_code' => 'people#activate', :as => :activate, :activation_code => nil
end

app/views/widgets/_footer_games.html.haml
= cache [:widget, :footer, :games] do
  %ul
    %li Игры
    - Category.games.each do |category|
      %li
        %a{:href => category_path(category)} #{category.title}

app/views/widgets/_leftbar_news.html.haml
= cache [Category, @category] do
  %h4 Новости
  %ul
    %li{:class => selected_class(!@category.blank? && @category.root?, "selected")}
      %a{:href => categories_path} все
    %li.nested
      %ul
        - Category.main.each do |category|
          %li{:class => selected_class(!@category.blank? && @category == category, "selected")}
            %a{:href => category_path(category)} #{category.title}
    /
      %li.arrow
        %a{:href => "#"} Архив

app/views/widgets/_login.html.haml
- if !logged_in?
  #login.signup
    %a.interactive{:href => signin_url} Вход
    или
    %a.interactive{:href => signup_url} регистрация
- else
  #login
    = current_person.greet
    %p
      = link_to "Выйти", session_path, :method => :delete, :confirm => "Уверены?"

app/views/widgets/_recent_articles.html.haml
= cache [Article, :widget, :recent_articles, current_person], :expires_in => 30.seconds do
  .item.articles
    %h4 Свежие статьи
    - Article.viewable_by(current_person).all(:limit => 5, :order => :id.desc).each do |article|
      .article
        .header          
          %div{:class => "icon #{article.icon}"}
          - if !article.approved?
            %div{:class => "icon pending"}
          %a{:href => article_path(article)} #{article.title}
        .clear
        %p #{article.extract}
    .clear